---
title: "JHUDSS C2"
author: "mdzakyjaya"
date: '2022-08-02'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 1 Data Types - Vector and Lists

## Matriks

pembuatan matriks dapat menggunakan pendefinisan dimensi dengan vector

```{r}
m <- 1:10
dim(m) <- c(2,5)
m
```

pembuatan matriks bisa juga menggunakan funsi cbind() dan rbinf()

```{r}
x <- c(1,3,4)
y <- c(3,4,1)
cmatriks <- cbind(x,y) # menyusun berdasarkan kolom
rmatriks <- rbinf(x,y) # menyusun berdararkan baris
```

## Factors

```{r}
x <- factor(c('laki', 'perempuan', 'laki', 'laki', 'perempuan'))
x
table(x) # membuat tabel berisi frequensi dari masing2 faktor
unclass(x) # melihat faktor dari masing value
```

R will order string alpabhetically if ordered levels not predefined
defining factors with ordered levels

```{r}
x <- factor(c('low', 'medium', 'low', 'high', 'low', 'medium'),
            levels = c('low', 'medium', 'high'))
table(x)
unclass(x)
```














