---
title: "C4 Exploratory Data Analysis"
author: "Dzaky Jaya"
date: '2022-08-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 1

## Create plot using Base System

Histogram
```{r}
data("airquality")
hist(airquality$Ozone)
```

Scatter Plot
```{r}
plot(airquality$Wind, airquality$Temp, xlab = 'wind', ylab = 'temp')
```

Boxplot
```{r}
boxplot(airquality$Ozone ~ airquality$Month, xlab = 'Month', ylab =
            'ozone',)
```

## Base Plot with Annotation
```{r}
plot(airquality$Wind, airquality$Temp, main = 'Temp vs Wind')

# annotate to previous plot without generating new plot
with(subset(airquality, Month == 6), points(Wind, Temp, col = 'blue', pch = 20))

with(subset(airquality, Month == 5), points(Wind, Temp, col = 'red', pch = 20))

legend('topright', pch = c(1, 20, 20), col = c(par('col'), 'blue', 'red'),
       legend = c('other', 'june', 'may'))
```

## Base plot with regression line
```{r}
reg <- lm(Temp ~ Wind, airquality)
abline(reg, lwd = 1)
```

## Multiple Base Plot
```{r}
par(mfrow = c(1, 3), oma = c(1,1,2,2))

with(airquality, {
    plot(Temp, Wind, main = 'Temp vs Wind')
    plot(Temp, Ozone, main = 'Temp vs Ozone')
    plot(Ozone, Wind, main = 'Ozone vs Wind')
})

mtext('Between Temp, Ozone and Wind', outer = T) #adding overall title
```

## copy plot from screen device to file graphics
```{r}
dev.copy2pdf()
dev.copy(jpeg)
```

# Week 3

## Hierarchical Clustering
```{r}
set.seed(1234)
par(mar = c(0, 0, 0, 0))

x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)

plot(x, y, pch = 19, col = 'blue', cex = 2)
text(x+0.05, y+0.05, labels = as.character(1:12))
```

count distance
```{r}
df <- data.frame(x = x, y = y)
dist(df)
```

creating dendogram
```{r}
distxy <- dist(df)
dendogram <- hclust(distxy)
plot(dendogram, xlab = '', ylab = '')
```

Heat Map
```{r}
set.seed(143)
dm <- as.matrix(df)[sample(1:12), ]
heatmap(dm)
```

## K-Means Clustering
```{r}
df <-data.frame(x, y)
kmeans <- kmeans(df, centers = 3)

kmeans
```

ploting clusters
```{r}
plot(x, y, col = kmeans$cluster, pch = 20)
points(kmeans$centers, pch = 3, col = c(1:3), lwd = 3)
```

kmeans using heatmap
```{r}
set.seed(1234)
dm <- as.matrix(df)[sample(1:12), ]
kmeans2 <- kmeans(dm, centers = 3)

par(mfrow = c(1,2))
image(t(dm)[, nrow(dm):1], yaxt = 'n')
image(t(dm)[, order(kmeans2$cluster)], yaxt = 'n')
```
